services:
  node-red:
    image: nodered/node-red:latest
    restart: unless-stopped
    environment:
      - TZ=UTC
    ports:
      - "1880:1880"
    volumes:
      - node-red-data:/data
    networks:
      - damiotdevnet

  n8n:
    image: n8nio/n8n:latest
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=pwddamdev
      - N8N_HOST=n8n
      - DB_TYPE=sqlite
      - DB_SQLITE_FILE=/home/node/.n8n/database.sqlite
      - WEBHOOK_URL=http://n8n:5678/
    volumes:
      - n8n_data:/home/node/.n8n 
    networks:
      - damiotdevnet
    
volumes:
  node-red-data:
  n8n_data: 